# .cargo/config.toml

[cargo-new]
vcs = "git"

[net]
retry = 3                   # network retries
git-fetch-with-cli = true   # use `git` executable for git ops

[registries.crates-io]
protocol = "sparse"
